### ISSUE TITLE
Mekanism updated which now breaks - Lasers, Weapons and Turrets mods

### ISSUE THREAD

**Issue by SirTwsted** [Ominox0/mekanism_lasers#1]
As the title says:
Mekanism updated which now breaks - Lasers, Weapons and Turrets mods.

I am using MC v1.21 with NEOForge v21.0.114, also tried it with v21.0.113

![Mekanism ERROR after update](https://github.com/user-attachments/assets/ae48657b-6947-4ae3-b85e-4330ba6c86f2)

![Screenshot_313](https://github.com/user-attachments/assets/2469d150-fcd6-4860-9555-6ce5b6be22c9)

end transmission:

**Comment by Ominox0** [comment]
Mekanism changed their code with an update, I still havent fix it yet, it will be fixed with newest mek lasers mod, and also i think mek turrets fixed it, try updating mek turrets, but idk about last mod

**Comment by SirTwsted** [comment]
Hi @Ominox0 ,
The person coding Turrets said that they are waiting to fix other things so a few things can be fixed at the same time.
Its still being worked on.  And doing lasers mod on its own still throws this same error message.  🤷‍♀️
And last mod I am still waiting on response.  I understand some people have RL 9-5 jobs like I do.
So I am patient  🤓👍

**Comment by Ominox0** [comment]
One thing you can do to fix the error is to downgrade mekanism mod, mekanism changed their code for floating long in new version of mekanism, so downgrading it should fix it, hopefully i will be able to fix the error by the end of the week 😀

**Comment by Ominox0** [comment]
@SirTwsted ! hi, newest update 1.1.2 for mekanism lasers fixed the issue, now unfortunately you have to wait for other mods to fix the API issue (if they have not yet :D)
