### ISSUE TITLE
Configuration keeps resetting

### ISSUE THREAD

**Issue by Saereth** [Ominox0/mekanism_lasers#4]
1.21.1 neoforge

The configs keep making .bak versions of themselves and resetting when I edit the blacklist, here is the modified file
https://gist.github.com/Saereth/50da6245553a9531ababfb935fab1fe9

and this is the one it reverts to
https://gist.github.com/Saereth/8ee039fb7611bfe6a63f1928cbd070f0

It might be easier just to do a tag based blacklist so you can just look for a mekanism_lasers:do_not_generate or something like that and pack devs can just apply the tag where needed

**Comment by Saereth** [comment]
I spoke with SkelMaxim and they said you were pretty busy lately but would be open to a PR, so Bysco worked with us to get this in for ya, hope all is well!
https://github.com/Ominox0/mekanism_lasers/pull/5

**Comment by Ominox0** [comment]
Thank you, the new version will be available soon on curseforge!

**Comment by Ominox0** [comment]
The new version was uploaded, if I made a typo in "Special thanks" please let me know so I can fix it.
